### PR TITLE
Added support for IE 11. closes #8

### LINKED ISSUE #8: IE Text Reversed
In IE 11, when you flip the card, the text is reversed and it does not show the back side of the card.

### PR DESCRIPTION
**Pull request by DrakeAnglin**
- Updated Poly Fills to support IE 11
- Added flipper style support for IE 11.
- Formatted scss file to nest front, back and rotate classes into main flipper class.

### CODE REVIEW

**Comment by DrakeAnglin** [comment]
@ritsrivastava01 Have you had a chance to review this pull request?

**Comment by ritsrivastava01** [comment]
@DrakeAnglin 
I saw but a bit doubtful as you changed so much in css. :(

**Comment by DrakeAnglin** [comment]
@ritsrivastava01 sorry i have a bad habit a refactoring code. I made only the required changes for this to work in IE.

**Comment by ritsrivastava01** [comment]
@DrakeAnglin  Thanks for considering it, now I saw it is minimal changes in CSS, but I need some time to cross-check that it is working perfectly in other browsers as well (chrome) OR you can confirm that as well if you have time.

Have a nice weekend.
Ritz

**Comment by ritsrivastava01** [comment]
OR you can share your stackblitz URL, I tried but got the error :
[https://stackblitz.com/github/DrakeAnglin/ngxFlip](https://stackblitz.com/github/DrakeAnglin/ngxFlip )

Ritz

**Comment by DrakeAnglin** [comment]
@ritsrivastava01 How is the testing going? would like to get this pulled into my project, but it must work in IE and Chrome.

**Comment by ritsrivastava01** [comment]
@DrakeAnglin I checked your branch locally and its working fine with Microsoft Edge but with IE 11 it through the same issue:
image
any idea how to fix it.
any counterpart will really helpful.
--Ritz

**Comment by ritsrivastava01** [comment]
@DrakeAnglin I merged the PR and updated the npm as well.
:)
now closing this PR request

**Comment by hakimio** [comment]
@DrakeAnglin @ritsrivastava01 this breaks it on Firefox.

**Comment by ritsrivastava01** [comment]
@hakimio  can u pls share the screenshot OR code on stackblitz.com ???

**Comment by hakimio** [comment]
After the last update it's actually broken in both Chrome and Firefox:

broken side menu
I am not doing anything special. Just using the component the following way:
```html
    <ngx-flip [flip]="menuFlipped">
        <ng-container
            front
            *ngTemplateOutlet="navigationTemplate; context: { foo: bar }"
        ></ng-container>
        <ng-container
            back
            *ngTemplateOutlet="navigationTemplate; context: { foo: baz }"
        ></ng-container>
    </ngx-flip>
```

**Comment by hakimio** [comment]
Just forgot to mention that I am using "ngx-flip" inside [Angular Material Sidenav](https://material.angular.io/components/sidenav/overview).

**Comment by ritsrivastava01** [comment]
can u try without Angular material, as in the last release, we (@DrakeAnglin ) enabled some fixes for IE 11, and we tested in chrome as well.

**Comment by hakimio** [comment]
It's still broken without Angular Material.
I guess "div.front" shouldn't have 0px height.
You can find just the generated html and CSS on [jsfiddle](http://jsfiddle.net/y37fcuj6/).
Some screenshots:
bug
flip-dom


Anyway, if you want to introduce major breaking changes like these, please release a new major version (8.0?) and revert this change in v7.0.

**Comment by hakimio** [comment]
@ritsrivastava01 Do you still need stackblitz example or you can already see the issue?

**Comment by ritsrivastava01** [comment]
@hakimio, I tested on stackblitz and it works fine. pls find the URL

https://stackblitz.com/edit/ngx-flip 

pls, check.

--Ritz

**Comment by ritsrivastava01** [comment]
Also, hope you can still use old version eg 6.1.1 Or others.

**Comment by hakimio** [comment]
@ritsrivastava01 
No, it does not work fine.
Same example broken with 7.0.3: https://stackblitz.com/edit/ngx-flip-tjakt4
Working with 7.0.2: https://stackblitz.com/edit/ngx-flip-cbt5gx (you might need to reinstall ngx-flip on stackblitz or test locally if stackblitz starts with incorrect ngx-flip version)

**Comment by ritsrivastava01** [comment]
yup you are right, but I compared the last two commit, (https://github.com/ritsrivastava01/ngxFlip/commit/d630d6c550fd908504d9a6ffe9def462e97f62a3)
there was the only change in the readme file.
I will look at the weekend.

Hope v7.0.2 will work for you OR if you have time, you then your help will be most appreciated.
 
--Ritz

**Comment by hakimio** [comment]
Must be [this commit](https://github.com/ritsrivastava01/ngxFlip/commit/413929ab1b5d3296687ac0fd9d34e0b57accb1a4).

**Comment by ritsrivastava01** [comment]
yup I hope ist by this line  'backface-visibility: hidden;'

but then how 7.0.2 is working?? because it was part of 7.0.2

**Comment by hakimio** [comment]
I don't think it was part of 7.0.2 which was released 5 months ago since the commit is part of this PR which you merged on 4th of May.

**Comment by ritsrivastava01** [comment]
will check and revert, if it not working..

**Comment by ritsrivastava01** [comment]
@hakimio , I fix and published new version(7.1.0) pls update it.

Thanks for your time and findings.

--Ritz

**Comment by hakimio** [comment]
@ritsrivastava01 Thanks :)

**Pull request merged**
