### PR TITLE
Angular 7 support plus other minor improvements

### PR DESCRIPTION
**Pull request by hakimio**
Angular 7 support and some other minor improvements

### CODE REVIEW

**Comment by ritsrivastava01** [comment]
thx for changes @hakimio, is it impact the npm package as well?

**Comment by hakimio** [comment]
@ritsrivastava01 the only real change to npm package is peer dependencies. But, yes, you need to publish a new package.

**Comment by ritsrivastava01** [comment]
Hi @hakimio ,
 I merged your PR, but I saw that you removed one simple test case. is there any reason to do that?

**Comment by hakimio** [comment]
@ritsrivastava01 yes, there is. It was failing because I removed unused "title" variable from AppComponent.

**Comment by ritsrivastava01** [comment]
@hakimio  Yes, I saw that as well, is there any reason to remove that title?
it's just for curiosity.

**Comment by hakimio** [comment]
Why would you need a public class property which you never use?
Static analysis was giving me a warning, so I removed it.

**Comment by hakimio** [comment]
Can you publish a new package on npm?

**Comment by ritsrivastava01** [comment]
I will do ASAP.. :)
Also many thanks for your contribution.

**Comment by hakimio** [comment]
@ritsrivastava01 Did you forget to publish a new package?

**Comment by hakimio** [comment]
@ritsrivastava01 Thanks for publishing new version. There is only one issue - you also added "ngx-flip-7.0.2.tgz" file to the package which shouldn't be there.

**Pull request merged**
